config/routes.rb
Rails.application.routes.draw do
  resources :reservations, only: [:index, :show, :new, :create, :edit, :destroy]
  resources :flights

  devise_for :users

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'flights#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
  paginates_per 10
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :flight

  validate :check_seat_availability

  def check_seat_availability
    if seat_class == "Economy"
      if flight.economy_seats_available < seat_count
        errors.add(:base, "There are not enough economy seats available for this flight.")
      else
        flight.update(economy_seats_available: flight.economy_seats_available - seat_count)
      end
    elsif seat_class == "Business"
      if flight.business_seats_available < seat_count
        errors.add(:base, "There are not enough business seats available for this flight.")
      else
        flight.update(business_seats_available: flight.business_seats_available - seat_count)
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  has_many :reservations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.page(params[:page])
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1 or /reservations/1.json
  def show
    @show = true
    @flight = Reservation.find(params[:id]).flight
  end



  # GET /reservations/1/edit
  def edit
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    @flight = Flight.find(params[:flight_id])
    @user = current_user
  end

  def create
    @reservation = current_user.reservations.build(reservation_params)
    @flight = Flight.find(params[:reservation][:flight_id])
    @user = current_user
    seat_type = params[:reservation][:seat_class]

    if seat_type == 'business'
      if @flight.business_class_seats < @reservation.count
        @reservation.errors.add(:count, "Not enough available seats in business class.")
        render :new and return
      end
      @flight.update(business_class_seats: @flight.business_class_seats - @reservation.count)
    elsif seat_type == 'economy'
      if @flight.economy_class_seats < @reservation.count
        @reservation.errors.add(:count, "Not enough available seats in economy class.")
        render :new and return
      end
      @flight.update(economy_class_seats: @flight.economy_class_seats - @reservation.count)
    end

    @reservation.update(pnr: SecureRandom.alphanumeric(6))

    if @reservation.save
      ReservationMailer.reservation_confirmation(@reservation, @flight, @user).deliver_now
      redirect_to @reservation, notice: 'Reservation was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    flight = @reservation.flight

    # Mise à jour des places du vol en ajoutant les places de la réservation supprimée
    if @reservation.seat_class == 'business'
      flight.business_class_seats += @reservation.count
    elsif @reservation.seat_class == 'economy'
      flight.economy_class_seats += @reservation.count
    end

    flight.save

    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:user_id, :flight_id, :count, :seat_class)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/application/index.html.erb
<h1>Bienvenue sur mon site</h1>
<p>Merci de visiter mon site.</p>

<%= link_to "Inscription", new_user_registration_path %>

<%= link_to "Connexion", new_user_session_path %>

<%= link_to 'Déconnexion', destroy_user_session_path, :method => :delete %>

app/views/flights/edit.html.erb
<h1>Flights#edit</h1>
<p>Find me in app/views/flights/edit.html.erb</p>

app/views/flights/index.html.erb
<%= stylesheet_link_tag "reserve", "data-turbo-track": "reload" %>

<h1 class="page-title">Flights</h1>

<section class="sectionVols mt-10">
  <div class="d-flex flex-column">
    <h1> Les Vols :</h1>

    <% @flights.each do |flight| %>
    <div class="wrapper">
      <div class="outer">
        <div class="content animated fadeInLeft d-flex">
          <div class="d-flex flexColumn m-20">
            <div class="d-flex justify-space-around">
              <div class="d-flex">
                <p class="titlePlace">Affaires : </p>
                <span class="bg animated fadeInDown"><%= flight.business_class_seats %></span>
              </div>
              <div class="d-flex">
                <p class="titlePlace">Economiques : </p>
                <span class="bg animated fadeInDown"><%= flight.economy_class_seats %></span>
              </div>
            </div>
            <h1>Numéro : <%= flight.number %></h1>
          </div>
          <div class="d-flex flexColumn m-20">
            <h1><%= flight.departure_airport %> => <%= flight.arrival_airport %></h1>
            <h3><td><%= flight.departure_date.strftime("%m/%d/%Y %I:%M %p") %></h3>
          </div>
          <div class="d-flex flexColumn m-20">
            <h3>Date d'arrivée :</h3>
            <h3><%= (flight.departure_date + flight.duration.minutes).strftime("%m/%d/%Y %I:%M %p") %></h3>
          </div>
          <div class="button m-5">
            <%= link_to "Réserver", new_reservation_path(flight_id: flight.id) %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
<%= paginate @flights %>

app/views/flights/new.html.erb
<h1>Flights#new</h1>
<p>Find me in app/views/flights/new.html.erb</p>

app/views/flights/show.html.erb
<h1>Flights#show</h1>
<p>Find me in app/views/flights/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PassPartour</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "formulaire", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <nav>
      <ul class="menu">
        <li class="logoImage"></li>
        <li class="logo"><%= link_to "PASS-PARTOUR", flights_path%></li>
        <li><%= link_to "Réservations", reservations_path, class: "buttonMenu" %></li>
        <li><%= link_to "Vols", flights_path, class: "buttonMenu" %></li>
        <% if current_user %>
          <li><%= link_to 'Déconnexion', destroy_user_session_path, method: :delete, class: "buttonMenu" %></li>
        <% else %>
          <li><%= link_to "Connexion", new_user_session_path, class: "buttonMenu" %></li>
        <% end %>
      </ul>
    </nav>
  </header>
    <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :flight_id, style: "display: block" %>
    <%= form.text_field :flight_id %>
  </div>

  <div>
    <%= form.label :count, style: "display: block" %>
    <%= form.number_field :count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<%= stylesheet_link_tag "reservation", "data-turbo-track": "reload" %>
<div class="container">
  <div class="row d-flex justify-content-center mt-5">
    <div class="col-12 col-md-8 col-lg-6 col-xl-5">
      <div class="card py-3 px-2">
        <div class="division">
          <div class="row">
            <div class="connexion"><span>Reservation n°<%= reservation.pnr %></span></div>
            <div class="col-3"><div class="line r"></div></div>
          </div>

          <% if @show %>
            <div class="form-group">
              <h3>Informations du vol</h3>
              <label>Aéroport de départ : <%= @flight.departure_airport %></label><br>
              <label>Aéroport d'arrivée : <%= @flight.arrival_airport %></label><br>
              <label>Heure de départ : <%= @flight.departure_date.strftime("%m/%d/%Y %I:%M %p") %></label><br>
              <label>Heure d'arrivée : <%= (@flight.departure_date + @flight.duration.minutes).strftime("%m/%d/%Y %I:%M %p") %></label><br>
              <label>Numéro de vol : <%= @flight.number %></label><br>
            </div>
            <h2>Vos informations</h2>
          <% else %>
            <div class="form-group">
              <label>Numéro de vol : <%= reservation.flight.number %></label>
            </div>
          <% end %>

          <div class="reservation-card__body">
            <div class="infos">
              <div class="reservation-card__label texte-white">Nombre de places : </div>
              <div class="reservation-card__value texte-white">&nbsp;<%= reservation.count %></div>
            </div>
            <div class="infos">
              <div class="reservation-card__label texte-white">Type : </div>
              <div class="reservation-card__value texte-white">&nbsp;<%= reservation.seat_class %></div>
            </div>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render "form", reservation: @reservation %>

                <div class="form-group mt-3">
                  <%= link_to "Retour aux réservations" , reservations_path , class:"btn btn-block btn-primary btn-lg" %>
                </div>
                <div class="form-group mt-3">
                  <%= link_to "Plus de détails", reservation , class:"btn btn-block btn-primary btn-lg"%>
                </div>
            </div>
          </div>
        </div>
      </div>
</div>
</div>

app/views/reservations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="titrePage">Reservations</h1>

<div id="reservations">
  <% @reservations.each do |reservation| %>
    <%= render reservation %>
    <div class="form-group mt-3">
      <%= link_to "Plus de détails", reservation , class:"btn btn-block btn-primary btn-lg"%>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
  <% end %>
</div>

app/views/reservations/new.html.erb
<%= stylesheet_link_tag "reservation", "data-turbo-track": "reload" %>
<div class="container">
  <div class="row d-flex justify-content-center mt-5">
    <div class="col-12 col-md-8 col-lg-6 col-xl-5">
      <div class="card py-3 px-2">
        <div class="division">
          <div class="row">
            <div class="connexion"><span>Reservation</span></div>
            <div class="col-3"><div class="line r"></div></div>
          </div>
        </div>
        <div class="form-group">
          <h3>Informations du vol</h3>
          <label>Aéroport de départ : <%= @flight.departure_airport %></label><br>
          <label>Aéroport d'arrivée : <%= @flight.arrival_airport %></label><br>
          <label>Heure de départ : <%= @flight.departure_date.strftime("%m/%d/%Y %I:%M %p") %></label><br>
          <label>Heure d'arrivée : <%= (@flight.departure_date + @flight.duration.minutes).strftime("%m/%d/%Y %I:%M %p") %></label><br>
          <label>Numéro de vol : <%= @flight.number %></label><br>
          <label>Places affaires restantes : <%= @flight.business_class_seats %></label><br>
          <label>Places économiques restantes : <%= @flight.economy_class_seats %></label>
        </div>
        <div class="form-group">
          <h3>Vos informations</h3>
          <label>Email : <%= current_user.email %></label><br>
        </div>
        <div class="division">
          <div class="row">
            <div class="col-3"><div class="line r"></div></div>
          </div>
        </div>
        <%= form_with(model: @reservation, local: true) do |form| %>
          <div class="hidden">
            <% if current_user %>
              <div class="form-group">
                <%= form.label :user_id %>
                <%= form.text_field :user_id, value: current_user.id, readonly: true %>
              </div>
            <% end %>
            <div class="form-group">
              <%= form.label :flight_id %>
              <%= form.hidden_field :flight_id, value: @flight.id %>
              <%= @flight.number %>
            </div>
          </div>
          <div class="form-group">
            <%= form.label "Nombre de places :" %>
            <%= form.number_field :count, class: 'form-control', min: 1, max: 99,required: true%>
          </div>
            <% if @reservation.errors.any? %>
            <div class="form-group">
              <div id="error_explanation">
                <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
                <ul>
                  <% @reservation.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
              </div>
            </div>
            <% end %>
          <div class="form-group">
            <%= form.label "Classe :" %>
            <%= form.select :seat_class, [['Affaires', 'business'], ['Economique', 'economy']], class: 'form-control' %>
          </div>
          <div class="form-group mt-3">
            <%= link_to 'Retour', reservations_path ,class: "btn btn-block btn-primary btn-lg" ,style: "width:100%"%>
          </div>
          <div class="form-group mt-3">
            <%= form.submit "Reserver" ,class:"btn btn-block btn-primary btn-lg"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<%= stylesheet_link_tag "reservation", "data-turbo-track": "reload" %>
<p style="color: green"><%= notice %></p>

<%= render @reservation %>

<div>
  <div class="form-group mt-3">
    <%= link_to "Retour aux réservations", reservations_path , class:"btn btn-block btn-primary btn-lg" %>
  </div>
  <div class="form-group mt-3">
    <%= button_to "Annuler cette réservation", @reservation, method: :delete , class:"btn btn-block btn-primary btn-lg" %>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>